//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekHackers_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Type
    {
        public int Emp_TypeID { get; set; }
        public string Employee_Type_Description { get; set; }
    }
}
