//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekHackers_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_ID { get; set; }
        public string Emp_FirstName { get; set; }
        public string Emp_SecondName { get; set; }
        public string Emp_Surname { get; set; }
        public string Emp_EmailAddress { get; set; }
        public string Gender { get; set; }
        public string Ethnicity { get; set; }
        public string Emp_PhysicalAddress { get; set; }
        public Nullable<int> Emp_TypeID { get; set; }
        public Nullable<System.DateTime> DateEmployed { get; set; }
        public Nullable<int> Emp_StatusID { get; set; }
        public string Image_Of_ID_Name { get; set; }
        public string Image_Of_ID_Path { get; set; }
        public string BankStatement_Image { get; set; }
        public string BankStatement_ImagePath { get; set; }
        public Nullable<int> TitleID { get; set; }
    }
}
