//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekHackers_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Sub_Total { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> CompanyAccountID { get; set; }
        public string CompanyName { get; set; }
    }
}
