//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekHackers_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Minutes
    {
        public int Meeting_MinutesID { get; set; }
        public Nullable<System.DateTime> Date_Taken { get; set; }
        public string Meeting_Agenda { get; set; }
        public string Meeting_Description { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> CompanyAccountID { get; set; }
    }
}
