//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekHackers_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public int QuotationID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CompanyAccountID { get; set; }
    }
}
