//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekHackers_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Supplier_ID { get; set; }
        public string CompanyName { get; set; }
        public string EmailAddress { get; set; }
        public string Cellphone { get; set; }
        public string PhysicalAddress { get; set; }
    }
}
