//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekHackers_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT
    {
        public int VAT_ID { get; set; }
        public Nullable<decimal> VAT_Percentage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
